# Generated by Django 5.0.3 on 2024-03-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_chair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Host',
            new_name='host',
        ),
    ]
